### ISSUE TITLE
issue - US20 - Soumission de l'article 

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#109]
**page**: article/draft/new/
**contexte**: Lorsque j'essaye de saisir un article en langue anglaise ou française.
**problème**: à la sauvegarde la page affiche -Internal Server Error-

**Comment by pointbar** [comment]
```bash
127.0.0.1 - - [18/Dec/2017 16:10:56] "POST /article/draft/new/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/core/helpers.py", line 40, in decorated_view
    return func(*args, **kwargs)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/articles/drafts/views.py", line 24, in create
    article = Article().save_from_request(request)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/articles/models.py", line 124, in save_from_request
    return self.save()
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/mongoengine/document.py", line 395, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: cafebabel.article index: original_article_1_language_1 dup key: { : null, : "en" })
```
