### ISSUE TITLE
Issue - US#25 - enregistrement de tag existant impossible

### ISSUE THREAD

**Issue by pointbar** [cafebabel/cafebabel.com#154]
**URL** : http://localhost:5000/article/draft/new/
**Contexte** : Lorsque j'ajoute un tag déjà présent dans la BD
**Problème** : À la sauvegarde j'ai une -internal server error- 

**Détail** : 
```bash
7.0.0.1 - - [17/Jan/2018 11:49:20] "GET /article/draft/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2018 11:49:24] "GET /article/draft/5a5e6fd276604b5460e7c1c5/?slug=lisbon-nomads-land HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2018 11:49:24] "GET /static/fonts/vremenagroteskitalic-webfont.woff2 HTTP/1.1" 304 -
127.0.0.1 - - [17/Jan/2018 11:49:34] "GET /article/draft/5a5e6fd276604b5460e7c1c5/edit/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2018 11:49:40] "GET /article/tag/suggest/?language=en&terms=plo HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2018 11:49:50] "POST /article/draft/5a5e6fd276604b5460e7c1c5/edit/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/articles/drafts/views.py", line 35, in edit
    article.save_from_request(request)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/articles/models.py", line 98, in save_from_request
    tag = Tag.objects.get_or_create(name=value, language=language)
  File "/Users/pntbr/Github/cafebabel.com/cafebabel/articles/tags/models.py", line 13, in get_or_create
    return self.get(**kwargs)
  File "/Users/pntbr/Github/cafebabel.com/venv/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 286, in get
    raise queryset._document.MultipleObjectsReturned(message)
cafebabel.articles.tags.models.MultipleObjectsReturned: 2 items returned, instead of 1
```

**Comment by davidbgk** [comment]
Est-ce que tu peux me détailler plus précisément les actions depuis un initdb qui amènent à cette erreur ?

**Comment by pointbar** [comment]
@davidbgk - En lisant tes échanges avec Vincent, j'ai l'impression que tu as avancé sur le sujet, la question est encore d'actualité ?

**Comment by davidbgk** [comment]
@pointbar il faudrait essayer de reproduire, je pense avoir corrigé celui-là ou plutôt le faire remonter plus tôt si ça se produit en usage normal

**Comment by pointbar** [comment]
@davidbgk j'ai testé et ça me semble être réglé.
